const menu = [
	{
		name:'常用',
		list:[
			{title:'日志',icon:'../../static/menu/ribao.png',url:'/pages/index/common-used/daily/add'},
			{title:'打卡',icon:'../../static/menu/daka.png',url:'/pages/index/no-page'},
			{title:'审批',icon:'../../static/menu/oashenpi.png',url:'/pages/index/common-used/oa/index'},
			{title:'每日一评',icon:'../../static/menu/meiriyiping.png',url:'/pages/index/other/comment/index'},
			{title:'绩效',icon:'../../static/menu/jixiao.png',url:'/pages/index/personnel/result/index'},
			{title:'添加',icon:'../../static/menu/tianjia.png',url:'/pages/index/no-page'}
		]
	},
	{
		name:'假勤管理',
		list:[
			{title:'打卡',icon:'../../static/menu/daka.png',url:'/pages/index/no-page'},
			{title:'请假申请',icon:'../../static/menu/qingjiashenqing.png',url:'/pages/index/no-page'},
			{title:'出差申请',icon:'../../static/menu/chuchaishenqing.png',url:'/pages/index/no-page'},
			{title:'外出申请',icon:'../../static/menu/waichushenqing.png',url:'/pages/index/no-page'},
			{title:'加班申请',icon:'../../static/menu/jiabanshenqing.png',url:'/pages/index/no-page'},
			{title:'补卡申请',icon:'../../static/menu/bukashenqing.png',url:'/pages/index/no-page'},
			// {title:'工时',icon:'../../static/menu/gongshi.png',url:'/pages/index/common-used/work-hours/add'}
		]
	},
	{
		name:'综合OA',
		list:[
			{title:'审批',icon:'../../static/menu/oashenpi.png',url:'/pages/index/common-used/oa/index'},
			{title:'日志',icon:'../../static/menu/rizhi.png',url:'/pages/index/common-used/daily/add'}
		]
	},
	{
		name:'智能人事',
		list:[
			{title:'员工信息',icon:'../../static/menu/yuangongxinxi.png',url:'/pages/index/no-page'},
			{title:'转正申请',icon:'../../static/menu/zhuanzhengshenqing.png',url:'/pages/index/no-page'},
			{title:'调动申请',icon:'../../static/menu/tiaogangshenqing.png',url:'/pages/index/no-page'},
			{title:'离职申请',icon:'../../static/menu/lizhishenqing.png',url:'/pages/index/no-page'},
			{title:'调薪申请',icon:'../../static/menu/tiaoxinshenqing.png',url:'/pages/index/no-page'},
			{title:'绩效',icon:'../../static/menu/jixiao.png',url:'/pages/index/personnel/result/index'}
		]
	},
	{
		name:'财务',
		list:[
			{title:'报销',icon:'../../static/menu/baoxiao.png',url:'/pages/index/no-page'},
			{title:'项目付款',icon:'../../static/menu/xiangmufukuan.png',url:'/pages/index/no-page'},
			{title:'备用金',icon:'../../static/menu/xiangmubeiyongjin.png',url:'/pages/index/no-page'},
			{title:'投标保证金',icon:'../../static/menu/toubiaobaozhengjin.png',url:'/pages/index/no-page'},
			{title:'中标服务费',icon:'../../static/menu/zhongbiaofuwufei.png',url:'/pages/index/no-page'},
			{title:'项目物资采购',icon:'../../static/menu/xiangmuwuzicaigou.png',url:'/pages/index/no-page'},
			{title:'开票',icon:'../../static/menu/kaipiao.png',url:'/pages/index/no-page'},
			{title:'收款',icon:'../../static/menu/shoukuan.png',url:'/pages/index/no-page'}
		]
	},
	{
		name:'行政',
		list:[
			{title:'用印申请',icon:'../../static/menu/yongyinshenqing.png',url:'/pages/index/no-page'}
		]
	},
	{
		name:'其他',
		list:[
			{title:'每日一评',icon:'../../static/menu/meiriyiping.png',url:'/pages/index/other/comment/index'},
			{title:'待办',icon:'../../static/menu/daiban.png',url:'/pages/message/components/wait'}
		]
	}
]
export default menu